plugins:
  - jekyll-scholar



collections:
  maps:
    output: true
    permalink: /maps/:name/
  developments:
    output: true
    permalink: /developments/:name/

defaults:
  - scope:
      path: ""
      type: "maps"
    values:
      layout: "map"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "developments"
    values:
      layout: "development_project"

scholar:
  style: apa