plugins:
  - jekyll-datapage-generator



collections:
  maps:
    output: true
    permalink: /maps/:name/

defaults:
  - scope:
      path: ""
      type: "maps"
    values:
      layout: "map"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'projects.features'
    template: 'development_project'
    name: 'id'
    name_expr: record['properties']['Project_Name']
    dir: 'developments'